### ISSUE TITLE
这个是可以用apache或nginx跑的吗，还是以服务方式运行？

### ISSUE THREAD

**Issue by uinux** [walkor/shadowsocks-php#1]
这个是可以用apache或nginx跑的吗，还是以服务方式运行？

**Comment by qqzj** [comment]
服务方式运行的呀,Workerman说明一切

**Comment by uinux** [comment]
我想问是否可以使用apache或nginx跑，而不是用linux服务，用服务不好监控流量呢。apache有现成的流量监控方案。

**Comment by walkor** [comment]
这个是单独的服务，和apache或nginx没有任何关系。如果非要扯上关系，可以用nginx在shadowsocks-php前面做一个tcp代理
