### ISSUE TITLE
Fatal error: Call to undefined function pcntl_signal() 

### ISSUE THREAD

**Issue by lovecn** [walkor/shadowsocks-php#10]
php Applications/Shadowsocks/start.php start -d

Fatal error: Call to undefined function pcntl_signal() in shadowsocks-php\Workerman\Lib\Timer.php on line 57

环境: win7 php7

**Comment by walkor** [comment]
要装pcntl扩展

**Comment by lovecn** [comment]
谢谢回复 但是 win 下木有` pcntl `扩展怎么办 http://stackmirror.bird.so/page/s0ugiiu78e2d

**Comment by walkor** [comment]
你的workerman不是最新的，用最新版本workerman试下。
