### ISSUE TITLE
high load after 2~10 minutes

### ISSUE THREAD

**Issue by sc104501** [walkor/shadowsocks-php#15]
From htop, I get all tcp worker with connections will cost 100% cpu.
but I think I have no connection now.
I test this in a new ubuntu 18 vm server but it happened again.

client: sslocal+polipo

Every 2.0s: php start.php status                                                           tdbrvm: Mon Dec  3 17:05:30 2018

Workerman[start.php] status
----------------------------------------------GLOBAL STATUS----------------------------------------------------
Workerman version:3.5.15          PHP version:7.2.10-0ubuntu0.18.04.1
start time:2018-12-03 16:51:46   run 0 days 0 hours
load average: 1.18, 1, 1         event-loop:\Workerman\Events\Select
2 workers       4 processes
worker_name        exit_status      exit_count
shadowsocks-server 0                0
shadowsocks-server 0                0
----------------------------------------------PROCESS STATUS---------------------------------------------------
pid     memory  listening          worker_name        connections send_fail timers  total_request qps    status
12846   2M      tcp://0.0.0.0:8888 shadowsocks-server 6           0         0       661           0      [idle]
12847   2M      tcp://0.0.0.0:8888 shadowsocks-server 0           0         0       721           0      [idle]
12848   2M      udp://0.0.0.0:8888 shadowsocks-server 0           0         0       0             0      [idle]
12849   2M      udp://0.0.0.0:8888 shadowsocks-server 0           0         0       0             0      [idle]
----------------------------------------------PROCESS STATUS---------------------------------------------------
Summary 8M      -                  -                  6           0         0       1382          0      [Summary]

**Comment by walkor** [comment]
Try to upgrade workerman.

**Comment by sc104501** [comment]
Thanks. High load no longer occurs.
