### ISSUE TITLE
请问给的这个测试账号的IP在哪配置

### ISSUE THREAD

**Issue by smallearth** [walkor/shadowsocks-php#2]
体验帐号
ip :45.55.93.159  
端口 :4431  
加密方式：aes-256-cfb  
密码：www.workerman.net  

请问给的这个测试账号的IP在哪配置？ 在配置文件里没有配置IP的选项啊。

我在这个地方填上那个ip，结果报错。
// 初始化worker，监听$PORT端口
$worker = new Worker('tcp://127.0.0.1:'.$PORT);

报错信息如下：
Workerman[start.php] start in DAEMON mode

Warning: stream_socket_server(): unable to connect to tcp://45.55.93.159:4431 (Cannot assign requested address) in /data/ifengsite/htdocs/shadowsocks-php-master/Workerman/Worker.php on line 1208

Fatal error: Uncaught exception 'Exception' with message 'Cannot assign requested address' in /data/ifengsite/htdocs/shadowsocks-php-master/Workerman/Worker.php:1211
Stack trace:
#0 /data/ifengsite/htdocs/shadowsocks-php-master/Workerman/Worker.php(404): Workerman\Worker->listen()
#1 /data/ifengsite/htdocs/shadowsocks-php-master/Workerman/Worker.php(321): Workerman\Worker::initWorkers()
#2 /data/ifengsite/htdocs/shadowsocks-php-master/start.php(32): Workerman\Worker::runAll()
#3 {main}
  thrown in /data/ifengsite/htdocs/shadowsocks-php-master/Workerman/Worker.php on line 1211

希望大神解答。

**Comment by walkor** [comment]
这个是客户端配置
先网上看下shadowsocks原理 和 配置教程吧

**Comment by smallearth** [comment]
明白了，多谢。

**Comment by walkor** [comment]
不客气
