### ISSUE TITLE
服务端一直提示part1 data uncorrect auth HMAC-SHA1

### ISSUE THREAD

**Issue by suhanyujie** [walkor/shadowsocks-php#21]
* 你好 walkor
* 昨天给vps重新装了下系统，然后装完PHP环境后，下载了shadowsocks-php 运行
* 运行后，每当我在本地用chrome访问时，shadowsocks-php一直在服务端打印如下内容：
>AuthAesProtocol auth_aes128_md5 uid:1 cid:f9e537d1 con:12
part1 data uncorrect auth HMAC-SHA1

* 之前的版本是能正常运行的，自从更新后，就无法运行，看了这个提示，是在`Applications/Shadowsocks/ShadowsocksProtocol.php`文件中，然而这个文件是后面新加的。。。
* 我vps的环境是`centOS6`,`php 7.3`

**Comment by walkor** [comment]
https://github.com/walkor/shadowsocks-php/commits/master/Applications/Shadowsocks/config.php
用老的配置试下，新的配置好像是默认用的新的授权方法
