### ISSUE TITLE
可以正常代理，有报错

### ISSUE THREAD

**Issue by javacty** [walkor/shadowsocks-php#6]
unsupported addrtype 127
unsupported addrtype 239
unsupported addrtype 162
unsupported addrtype 204
unsupported addrtype 196
unsupported addrtype 35
unsupported addrtype 67
unsupported addrtype 61
unsupported addrtype 64

**Comment by walkor** [comment]
这个是打印的日志，不是报错。
输出日志原因连接发来的包不符合预期的数据，一般是由于错误的用户名密码导致，或者一些网络嗅探工具发来的包等等，不用理会。

**Comment by javacty** [comment]
非常感谢
另外测试了下，hhvm下也可运行。

有个奇怪的是：
搜狐可以访问，新浪缺不能访问（php和hhvm下都是）

**Comment by walkor** [comment]
不是php或者hhvm问题，你的服务器访问不到home.sina.com。
你可以在你的服务器上```ping home.sina.com``` 试下。
