### ISSUE TITLE
exception 'Exception' with message 'class \Protocols\ not exist'  错误

### ISSUE THREAD

**Issue by xpader** [walkor/shadowsocks-php#8]
一直运行很稳定，就这一次进程异常退出 ，status 64000

系统 FreeBSD 10.3 x64，PHP 5.6.28 + libevent，Workerman 3.3.4

错误是找不到 \Protocols\ 类，奇怪的是 AsyncnTcpConnection 地址居然构造参数是 tcp://:27688，只有端口号没有主机地址，有可能是发了什么不合格的包，这块是否有问题或者容错处理？

另外，能不能对一些新的特性和加密算法提供支持？

2017-02-21 09:34:07 pid:64624 exception 'Exception' with message 'class \Protocols\ not exist' in /usr/home/freebsd/WorkermanApps/Workerman/Connection/AsyncTcpConnection.php:121
Stack trace:
#0 /usr/home/freebsd/WorkermanApps/Applications/Shadowsocks/server.php(88): Workerman\Connection\AsyncTcpConnection->__construct('tcp://:27688')
#1 [internal function]: {closure}(Object(Workerman\Connection\TcpConnection), '\xA4\xAE\xB1\xBC\x11\xB1,me\x19\xB1e\xF2\xCF\x8E...')
#2 /usr/home/freebsd/WorkermanApps/Workerman/Connection/TcpConnection.php(456): call_user_func(Object(Closure), Object(Workerman\Connection\TcpConnection), '\xA4\xAE\xB1\xBC\x11\xB1,me\x19\xB1e\xF2\xCF\x8E...')
#3 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #47593, 2, NULL)
#4 /usr/home/freebsd/WorkermanApps/Workerman/Events/Libevent.php(202): event_base_loop(Resource id #31)
#5 /usr/home/freebsd/WorkermanApps/Workerman/Worker.php(1470): Workerman\Events\Libevent->loop()
#6 /usr/home/freebsd/WorkermanApps/Workerman/Worker.php(898): Workerman\Worker->run()
#7 /usr/home/freebsd/WorkermanApps/Workerman/Worker.php(864): Workerman\Worker::forkOneWorker(Object(Workerman\Worker))
#8 /usr/home/freebsd/WorkermanApps/Workerman/Worker.php(420): Workerman\Worker::forkWorkers()
#9 /usr/home/freebsd/WorkermanApps/start.php(42): Workerman\Worker::runAll()
#10 {main}
2017-02-21 09:34:07 pid:64624 WORKER EXIT UNEXPECTED 
2017-02-21 09:34:08 pid:64622 worker[shadowsocks-server:64624] exit with status 64000

**Comment by walkor** [comment]
应该是客户端发了一个host为空的数据包导致的，现在做了兼容。
新的特性是指？
加密算法目前支持
```
        'aes-128-cfb'
        'aes-192-cfb'
        'aes-256-cfb'
        'bf-cfb'
        'camellia-128-cfb'
        'camellia-192-cfb'
        'camellia-256-cfb'
        'cast5-cfb'
        'des-cfb'
        'idea-cfb'
        'rc2-cfb'
        'seed-cfb'
```

**Comment by xpader** [comment]
比如更多的加密算法支持，比如 AEAD 之类的，或者集成现在的 KCP 等等。

**Comment by walkor** [comment]
目前看加密算法够用了，
多一个少一个没有区别。

KCP不知道是什么东西
