### ISSUE TITLE
最新的win客户端连不上这php版的server端

### ISSUE THREAD

**Issue by lamwood** [walkor/shadowsocks-php#9]
我用这个版本的在linux搭建了一个server端，用shadowsocks-windows-3.x.x版本以上的客户端连接服务端后网页是没法打开的，用shadowsocks-windows-2.5.8连接就能正常打开网页.然后调试了一下server.php脚本,发现3以上的客户端发到客户端的$buffer,用
![image](https://cloud.githubusercontent.com/assets/15353684/26443037/6c266650-4169-11e7-9105-87529576a348.png)
这个php解析socket5方法没法正常解析数据，我强制把$addr_type设置为3，后得到$addr_type, $dest_addr, $dest_port,都是正确的，但是网页确实无法打开，到网页服务器看日志，发现请求的信息变成乱码
![image](https://cloud.githubusercontent.com/assets/15353684/26443310/63004522-416a-11e7-9db5-22a848f08781.png)

请问我该怎么改动才能让这个版本的服务端适应最新的SS客户端？

**Comment by walkor** [comment]
需要了解shadowsocks-windows-3.x.x 和 shadowsocks-windows-2.5.8通讯机制有什么区别。根据区别去更改服务端逻辑。

**Comment by lamwood** [comment]
搞错了，原来我电脑没装.netframwork4.6.2
